CREATE TABLE CLIENTS (
	ID BIGSERIAL PRIMARY KEY,
	CLIENT_ID VARCHAR(255) NOT NULL,
	CLIENT_SECRET VARCHAR(255),
	RESOURCE_IDS VARCHAR(255),
	SCOPES VARCHAR(255),
	GRANT_TYPES VARCHAR(255),
	AUTHORITIES VARCHAR(255)
);