CREATE TABLE WINE (
	ID BIGSERIAL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	YEAR INTEGER,
	PRODUCER VARCHAR(255),
	COUNTRY VARCHAR(255),
	REGION VARCHAR(255),
	QUANTITY INTEGER NOT NULL,
	PRICE NUMERIC(10, 2),
	MERCHANT VARCHAR(255) NOT NULL
);